name: Release Binary

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu,x86_64-unknown-linux-gnu,x86_64-apple-darwin,aarch64-apple-darwin

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf musl-tools build-essential

      - name: Build Linux x86_64
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Build Linux aarch64
        run: cargo build --release --target aarch64-unknown-linux-gnu

      - name: Build macOS x86_64
        run: cargo build --release --target x86_64-apple-darwin

      - name: Build macOS aarch64
        run: cargo build --release --target aarch64-apple-darwin

      - name: Package Binaries
        run: |
          mkdir -p release
          cp target/x86_64-unknown-linux-gnu/release/hippius-libp2p release/hippius-libp2p-linux-x86_64
          cp target/aarch64-unknown-linux-gnu/release/hippius-libp2p release/hippius-libp2p-linux-aarch64
          cp target/x86_64-apple-darwin/release/hippius-libp2p release/hippius-libp2p-darwin-x86_64
          cp target/aarch64-apple-darwin/release/hippius-libp2p release/hippius-libp2p-darwin-aarch64
          cd release
          sha256sum * > checksums.txt
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/hippius-libp2p-linux-x86_64
            release/hippius-libp2p-linux-aarch64
            release/hippius-libp2p-darwin-x86_64
            release/hippius-libp2p-darwin-aarch64
            release/checksums.txt
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
